export const servicesData =  {
    categories: ['All', 'Africa', 'Americas', 'Asia', 'Europe', 'Middle East'],
    services: [
        { id: 1, image: '/assets/img/Services/athens-1.jpg', title: 'Athens', category: 'Europe', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/Services/london-1.jpg', title: 'London', category: 'Europe', description: 'A description of our service...', cost: 15000 },
        { id: 3, image: '/assets/img/Services/iceland-1.jpg', title: 'Iceland', category: 'Europe', description: 'A description of our service...', cost: 5000 },
        { id: 4, image: '/assets/img/Services/petra-1.jpg', title: 'Petra', category: 'Middle East', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/Services/singapore-1.jpg', title: 'Singapore', category: 'Asia', description: 'A description of our service...', cost: 7500 },
        { id: 6, image: '/assets/img/Services/chichenitza-1.jpg', title: 'Chichenitza ', category: 'Americas', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/Services/rome-1.jpg', title: 'Rome', category: 'Europe', description: 'A description of our service...', cost: 8000 },
        { id: 8, image: '/assets/img/Services/tajmahal-1.jpg', title: 'Taj Mahal', category: 'Asia', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/Services/stock/service-9.jpg', title: 'Couples Day', category: 'Water', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/assets/img/Services/stock/service-10.jpg', title: 'Pedicure', category: 'Ammenities', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/Services/stock/service-11.jpg', title: 'Girls Day', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/Services/stock/service-12.jpg', title: 'Group Gathering', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/assets/img/Services/stock/service-13.jpg', title: 'Cold and Hot Treament', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/assets/img/Services/stock/service-14.jpg', title: 'Service 14', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/assets/img/Services/stock/service-15.jpg', title: 'Full Body Scrub', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/Services/stock/service-16.jpg', title: 'Deep tissue', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/assets/img/Services/stock/service-17.jpg', title: 'Hot Stone Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/assets/img/Services/stock/service-18.jpg', title: 'Hot, Cold and In Between', category: 'Water', description: 'A description of our service...', cost: 3500 },
        { id: 19, image: '/assets/img/Services/stock/service-19.jpg', title: 'Me Time', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 20, image: '/assets/img/Services/stock/service-20.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}