export const servicesData =  {
    categories: ['All', 'Africa', 'Americas', 'Asia', 'Europe', 'Middle East'],
    services: [
        { id: 1, image: '/assets/img/Services/athens-1.jpg', title: 'Athens', category: 'Europe', description: 'Athens, Greece', cost: 5736 },
        { id: 2, image: '/assets/img/Services/london-1.jpg', title: 'London', category: 'Europe', description: 'London, England', cost: 92657 },
        { id: 3, image: '/assets/img/Services/iceland-1.jpg', title: 'Reykjavik', category: 'Europe', description: 'Reykjavik, Iceland', cost: 345 },
        { id: 4, image: '/assets/img/Services/petra-1.jpg', title: 'Petra', category: 'Middle East', description: 'Aqaba, Egypt', cost: 75982 },
        { id: 5, image: '/assets/img/Services/singapore-1.jpg', title: 'Singapore', category: 'Asia', description: 'A description of our service...', cost: 356 },
        { id: 6, image: '/assets/img/Services/chichenitza-1.jpg', title: 'Chichenitza ', category: 'Americas', description: 'A description of our service...', cost: 28456 },
        { id: 7, image: '/assets/img/Services/rome-1.jpg', title: 'Rome', category: 'Europe', description: 'A description of our service...', cost: 435 },
        { id: 8, image: '/assets/img/Services/tajmahal-1.jpg', title: 'Taj Mahal', category: 'Asia', description: 'A description of our service...', cost: 23654 },
        { id: 9, image: '/assets/img/Services/rushmore-1.jpg', title: 'Mount Rushmore', category: 'Americas', description: 'A description of our service...', cost: 24121 },
        { id: 10, image: '/assets/img/Services/morocco-2.jpg', title: 'Marrakech', category: 'Africa', description: 'Marrakech, Morocco', cost: 6737 },
        { id: 11, image: '/assets/img/Services/capetown-1.jpg', title: 'Cape Town', category: 'Africa', description: 'Cape Town, South Africa', cost: 4633 },
        { id: 12, image: '/assets/img/Services/egypt-1.jpg', title: 'Giza', category: 'Africa', description: 'Giza, Egypt', cost: 79476 },
        { id: 13, image: '/assets/img/Services/bergen-2.jpg', title: 'Bergen', category: 'Europe', description: 'Bergen, Norway', cost: 43562 },
        { id: 14, image: '/assets/img/Services/amsterdam-1.jpg', title: 'Amsterdam', category: 'Europe', description: 'Amsterdam, Netherlands', cost: 347 },
        { id: 15, image: '/assets/img/Services/oslo-1.jpg', title: 'Oslo', category: 'Europe', description: 'Oslo, Norway', cost: 75454 },
        { id: 16, image: '/assets/img/Services/hongkong-1.jpg', title: 'Hong Kong', category: 'Asia', description: 'Hong Kong, China', cost: 7654 },
        { id: 17, image: '/assets/img/Services/florence-1.jpg', title: 'Florence', category: 'Europe', description: 'Florence, Italy', cost: 4928 },
        { id: 18, image: '/assets/img/Services/chiangmai-1.jpg', title: 'Chiang Mai', category: 'Asia', description: 'Chiang Mai, Thailand', cost: 37280 },
        { id: 19, image: '/assets/img/Services/cartagena-1.jpg', title: 'Cartagena', category: 'Americas', description: 'Cartagena, Colombia', cost: 83658 },
        { id: 20, image: '/assets/img/Services/beirut-1.jpg', title: 'Beirut', category: 'Middle East', description: 'Beirut, Lebanon', cost: 352 },
    ],
}